name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on: [ push, pull_request ]

jobs:
  jest:
    runs-on: ubuntu-latest
    environment: development
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn global add lerna
    - run: lerna bootstrap
    - run: lerna run test
    - name: Archive npm failure logs
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: npm-logs
        path: ~/.npm/_logs
  lint:
    runs-on: ubuntu-latest
    environment: development
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: echo $ACCESS_TOKEN_SECRET
    - run: yarn global add lerna
    - run: lerna bootstrap
    - run: lerna run lint
    - name: Archive npm failure logs
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: npm-logs
        path: ~/.npm/_logs
  
  build:
    needs: [ jest, lint ]
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 19.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn global add lerna
    - run: lerna bootstrap
    - run: lerna run build
    - name: Archive npm failure logs
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: npm-logs
        path: ~/.npm/_logs
